app/course/forms.py
# -*- coding: utf-8 -*-
from flask.ext.wtf import Form
from wtforms import StringField, IntegerField, SelectField, SubmitField, TextAreaField
from wtforms.validators import Length, Required
from wtforms.widgets.html5 import TelInput

__author__ = 'scott'


class CoursePublishForm(Form):
    title = StringField(u'标题', validators = [Length(1, 64)])
    name = StringField(u'课程名', validators = [Length(1, 64)])
    brief = StringField(u'简要描述')
    detailed = TextAreaField(u'详细描述')
    price = IntegerField(u'价格')
    contact = StringField(u'联系人')
    telephone = StringField(u'联系电话')
    category = SelectField(u'分类')
    company = StringField(u'公司名称')
    submit = SubmitField(u'发布')

    def __init__(self, *args, **kwargs):
        super(CoursePublishForm, self).__init__(*args, **kwargs)
        self.category.choices = [('language_trainning', u'语言培训')]


class ApplicationForm(Form):
    name = StringField(u'姓名', validators=[Required()])
    tel = StringField(u'联系电话', validators=[Required()])
    address = StringField(u'联系地址')
    submit = SubmitField(u'确认')


class CommentForm(Form):
    body = StringField(u'输入你的评论', validators=[Required()])
    submit = SubmitField(u'提交')

app/course/__init__.py
# -*- coding: utf-8 -*-

__author__ = 'scott'

from flask import Blueprint

course = Blueprint('course', __name__)

from . import views
from ..models import Permission


@course.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/course/views.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, url_for, redirect, current_app, request
from flask.ext.login import login_required, current_user
from app import db
from app.course import course
from app.course.forms import CoursePublishForm, CommentForm, ApplicationForm
from app.decorators import permission_required
from app.models import Permission, Course, Comment, Application, User

__author__ = 'scott'

# Attention: 方法名不能是course！会与蓝图命名冲突！
# TODO-cott: 修改蓝图命名？


@course.route('/', methods=['GET', 'POST'])
def course_index():
    page = request.args.get('page', 1, type=int)
    pagination = Course.query.order_by(Course.timestamp.desc()).paginate(
        page, per_page=current_app.config['SONGXUE_POSTS_PER_PAGE'],
        error_out=False)
    courses = pagination.items
    return render_template('course_index.html', courses=courses,
                           pagination=pagination)


@course.route('/<int:id>', methods=['GET', 'POST'])
def detail(id):
    courses = Course.query.get_or_404(id)
    # print current_user.is_applied_by(courses)
    form = CommentForm(prefix="comment-form")
    if form.validate_on_submit():
        comment = Comment(body=form.body.data,
                          course=courses,
                          author=current_user._get_current_object())
        db.session.add(comment)
        flash(u'你的评论已发布。')
        return redirect(url_for('course.detail', id=courses.id, page=-1))
    application_form = ApplicationForm(prefix="application")
    if application_form.validate_on_submit():
        application = Application()
        flash(u'报名成功！')
        return redirect(url_for('course.detail', id=courses.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (courses.comments.count() - 1) / \
               current_app.config['SONGXUE_COMMENTS_PER_PAGE'] + 1
    pagination = courses.comments.order_by(Comment.timestamp.asc()).paginate(
        page, per_page=current_app.config['SONGXUE_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items
    # courses = [courses] 为course.html中courses[0].id,转化为list,否则会报错
    return render_template('course/course.html', form=form, courses=[courses],
                           comments=comments, pagination=pagination,
                           application_form=application_form)


@course.route('/publish', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.PUBLISH_COURSES)
def publish():
    form = CoursePublishForm()
    if form.validate_on_submit():
        course = Course(title=form.title.data,
                        name=form.name.data,
                        brief=form.brief.data,
                        detailed=form.detailed.data,
                        price=form.price.data,
                        contact=form.contact.data,
                        telephone=form.telephone.data,
                        category=form.category.data,
                        company=form.company.data,
                        publisher=current_user._get_current_object())
        db.session.add(course)
        flash(u'你的课程已发布。')
        return redirect(url_for('.publish', form=form))
    return render_template('course/publish.html', form=form)


@course.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.PUBLISH_COURSES)
def edit(id):
    course = Course.query.get_or_404(id)
    form = CoursePublishForm()
    if form.validate_on_submit():
        course.title = form.title.data
        course.name = form.name.data
        course.brief = form.brief.data
        course.detailed = form.detailed.data
        course.price = form.price.data
        course.contact = form.contact.data
        course.telephone = form.telephone.data
        course.category = form.category.data
        course.company = form.company.data
        db.session.add(course)
        flash(u'你的课程已修改。')
        return redirect(url_for('course.detail', id=course.id, page=-1))
    form.title.data = course.title
    form.name.data = course.name
    form.brief.data = course.brief
    form.detailed.data = course.detailed
    form.price.data = course.price
    form.contact.data = course.contact
    form.telephone.data = course.telephone
    form.category.data = course.category
    form.company.data = course.company
    return render_template('course/edit.html', form=form)


@course.route('/application/<int:id>', methods=['POST'])
@login_required
def application(id):
    # TODO-cott: 优化表单，并了解安全方面
    course = Course.query.filter_by(id=id).first()
    if course is None:
        flash(u'错误的课程。')
        return redirect(url_for('course.detail', id=id, page=-1))
    if current_user.is_applied_by(course):
        flash(u'你已报名。')
        return redirect(url_for('course.detail', id=id, page=-1))
    if not course.is_appled_by(current_user):
        ap = Application(name=request.form['application-name'],
                         telephone=request.form['application-tel'],
                         address=request.form['application-address'],
                         applicant=current_user._get_current_object(),
                         apply_course=course)
        db.session.add(ap)
        flash(u'报名成功')
        return redirect(url_for('course.detail', id=id, page=-1))
    return redirect(url_for('course.detail', id=id, page=-1))


@course.route('/applications', methods=['GET', 'POST'])
@login_required
def applications():
    """显示所有课程的报名表，按课程分类"""
    page = request.args.get('page', 1, type=int)
    pagination = current_user.applied \
        .order_by(Application.timestamp.asc()) \
        .paginate(page, per_page=current_app.config['SONGXUE_COMMENTS_PER_PAGE'],
                  error_out=False)
    apls = pagination.items
    return render_template('course/applications.html', apls=apls,
                           pagination=pagination)


@course.route('/application_summary', methods=['GET', 'POST'])
@login_required
@permission_required(Permission.PUBLISH_COURSES)
def application_summary():
    page = request.args.get('page', 1, type=int)
    pagination = Application.query \
        .join(Course) \
        .join(User) \
        .filter(Course.author_id == current_user.id) \
        .order_by(Application.timestamp.asc()) \
        .paginate(page, per_page=current_app.config['SONGXUE_COMMENTS_PER_PAGE'],
                  error_out=False)
    apls = pagination.items
    # ps: apls[0].apply_course.publisher 是课程发布者,apls[0].applicant 是课程申请者(报名人)
    return render_template('course/application_summary.html', apls=apls,
                           pagination=pagination)


@course.route('/<int:id>/weixin/application', methods=['GET', 'POST'])
def weixin_application(id):
    course = Course.query.get_or_404(id)
    form = ApplicationForm()
    if form.validate_on_submit():
        flash(u"报名成功！")
        return redirect(url_for('course.weixin_application', id=id))
    return render_template('course/weixin_application.html', form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}松学网{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">松学网</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">首页</a></li>
                    <li><a href="{{ url_for('main.index') }}">课程</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.can(Permission.PUBLISH_COURSES) %}
                        <li><a href="{{ url_for('course.application_summary') }}">报名汇总</a></li>
                    {% endif %}
                    {% if current_user.can(Permission.MODERATE_USERS) %}
                        <li><a href="{{ url_for('main.moderate_users') }}">用户审核</a></li>
                    {% endif %}
                    {% if current_user.can(Permission.MODERATE_COMMENTS) %}
                        <li><a href="{{ url_for('main.moderate_comments') }}">评论审核</a></li>
                    {% endif %}
                    {% if current_user.is_authenticated() %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ current_user.gravatar(size=18) }}">
                                {{ current_user.username }}
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                {% if current_user.can(Permission.PUBLISH_COURSES) %}
                                    <li><a href="{{ url_for('course.publish') }}">发布课程</a></li>
                                {% endif %}
                                <li><a href="{{ url_for('course.applications') }}">我的报名</a></li>
                                {% if current_user.is_authenticated() %}
                                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">个人资料</a></li>
                                {% endif %}
                                <li><a href="{{ url_for('auth.change_password') }}">修改密码</a></li>
                                <li><a href="{{ url_for('auth.change_email_request') }}">修改邮箱</a></li>
                                <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang("zh-cn") }}
{% endblock %}

app/templates/course_index.html
{% extends "theme_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}松学网 - 课程{% endblock %}

{% block content_main %}
    {% include '_courses.html' %}
    {% if pagination %}
        <div class="pagination">
            {{ macros.pagination_widget(pagination, '.course_index') }}
        </div>
    {% endif %}
{% endblock %}

app/templates/edit_post.html
{% extends "theme_base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}松学网 - 编辑 Post{% endblock %}

{% block content_main %}
    <div class="page-header">
        <h1>编辑 Post</h1>
    </div>
    <div>
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/homepage.html
{% extends "bootstrap/base.html" %}

{% block title %}松学网{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link href="{{ url_for('static', filename="css/templatemo_style.css") }}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">松学网</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">首页</a></li>
                    <li><a href="{{ url_for('main.index') }}">课程</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.can(Permission.PUBLISH_COURSES) %}
                        <li><a href="{{ url_for('course.application_summary') }}">报名汇总</a></li>
                    {% endif %}
                    {% if current_user.can(Permission.MODERATE_USERS) %}
                        <li><a href="{{ url_for('main.moderate_users') }}">用户审核</a></li>
                    {% endif %}
                    {% if current_user.can(Permission.MODERATE_COMMENTS) %}
                        <li><a href="{{ url_for('main.moderate_comments') }}">评论审核</a></li>
                    {% endif %}
                    {% if current_user.is_authenticated() %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ current_user.gravatar(size=18) }}">
                                {{ current_user.username }}
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                {% if current_user.can(Permission.PUBLISH_COURSES) %}
                                    <li><a href="{{ url_for('course.publish') }}">发布课程</a></li>
                                {% endif %}
                                <li><a href="{{ url_for('course.applications') }}">我的报名</a></li>
                                {% if current_user.is_authenticated() %}
                                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">个人资料</a>
                                    </li>
                                {% endif %}
                                <li><a href="{{ url_for('auth.change_password') }}">修改密码</a></li>
                                <li><a href="{{ url_for('auth.change_email_request') }}">修改邮箱</a></li>
                                <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div id="home">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}
            <div id="templatemo_slider">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="{{ url_for('static', filename="03.jpg") }}" alt="01.jpg">

                            <div class="carousel-caption">
                                <h3>940 x xxx</h3>
                            </div>
                        </div>
                        <div class="item">
                            <img src="{{ url_for('static', filename="03.jpg") }}" alt="02.jpg">

                            <div class="carousel-caption">
                                <h3>940 x xxx</h3>
                            </div>
                        </div>
                        <div class="item">
                            <img src="{{ url_for('static', filename="03.jpg") }}" alt="03.jpg">

                            <div class="carousel-caption">
                                <h3>940 x xxx</h3>
                            </div>
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div id="templatemo_main">
                <div class="col one_third fp_services">
                    <h2>你好， {% if current_user.is_authenticated() %}{{ current_user.username }}{% else %}
                        陌生人{% endif %}！</h2>
                    <img src="{{ url_for('static', filename="images/templatemo_image_04.jpg") }}" alt="图片"
                         class="image_fl"/>

                    <p>
                        <a href="http://www.templatemo.com" target="_parent">Carousel</a>
                        is free css template provided by
                        <a href="http://www.templatemo.com">templatemo.com</a>
                        for your personal or commercial websites. Quisque nec suscipit ipsum. Fusce vitae accumsan
                        massa.
                    </p>
                    <ul class="templatemo_list">
                        <li class="flow">Integer placerat dolor vel</li>
                        <li class="flow nomr">Condimentum vulputate</li>
                        <li class="flow">Itristique non suscipit id</li>
                        <li class="flow nomr"> Donec eget lacus vitae leo</li>
                    </ul>
                </div>
                <div class="col one_third fp_services">
                    <h2>最近公告</h2>

                    <div class="rp_pp">
                        <img src="{{ url_for('static', filename="images/templatemo_image_01.jpg") }}" alt="Image 01"/>
                        <a href="#">Integer venenatis pharetra magna vitae condimentum  ultrices.</a>

                        <p>Feb 27, 2048 - 140 comments</p>

                        <div class="cleaner"></div>
                    </div>
                    <div class="rp_pp">
                        <img src="{{ url_for('static', filename="images/templatemo_image_02.jpg") }}" alt="Image 02"/>
                        <a href="#">Nulla facilisi. Vestibulum vel odio ac mi feugiat condimentum.</a>

                        <p>Feb 21, 2048 - 154 comments</p>

                        <div class="cleaner"></div>
                    </div>
                    <div class="rp_pp">
                        <img src="{{ url_for('static', filename="images/templatemo_image_03.jpg") }}" alt="Image 03"/>
                        <a href="#">Fusce dolor neque, placerat ac erat venenatis eu, venenatis ac leo.</a>

                        <p>Feb 15, 2048 - 179 comments</p>

                        <div class="cleaner"></div>
                    </div>
                </div>
                <div class="col one_third no_margin_right fp_services">
                    <h2>Testimonials</h2>

                    <div class="testimonial">
                        <p>Nunc vitae purus non augue scelerisque ultricies vitae et velit quis nulla id orci malesua
                            tempus
                            erat.</p>
                        <cite>Rock <a href="#"><span>- CEO, New Company</span></a></cite></div>
                    <div class="testimonial">
                        <p>Curabitur sed felis urna, quis eleifend magna. Nunc quam mollis sem iaculis sed. Validate <a
                                href="http://validator.w3.org/check?uri=referer"
                                rel="nofollow"><strong>XHTML</strong></a>
                            &amp; <a
                                    href="http://jigsaw.w3.org/css-validator/check/referer"
                                    rel="nofollow"><strong>CSS</strong></a>.</p>
                        <cite>John <a href="#"><span>- Senior Director, Company</span></a></cite></div>
                </div>

                <div class="cleaner"></div>
            </div>
            <!-- END of templatemo_main -->
        {% endblock %}
        {% block page_footer %}
            <div id="templatemo_bottom_wrapper">
                <div id="templatemo_bottom">
                    <div class="col one_third">
                        <h4><span></span>博客</h4>

                        <div class="bottom_box">
                            <ul class="footer_list">
                                并没有什么博客
                            </ul>
                        </div>
                    </div>
                    <div class="col one_third">
                        <h4><span></span>更新公告</h4>

                        <div class="bottom_box">
                            <ul class="twitter_post">
                                <li>并没有什么更新</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col one_third no_margin_right">
                        <h4><span></span>关于我们</h4>

                        <div class="bottom_box">
                            <p>并没有什么</p>
                        </div>
                    </div>
                    <div class="cleaner"></div>
                </div>
                <!-- END of tempatemo_bottom -->
            </div>
            <!-- END of tempatemo_bottom_wrapper -->
            <div id="templatemo_footer_wrapper">
                <div id="templatemo_footer">
                    Copyright © 2015 松学网 |
                    由 <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a> 设计
                    曾科特 修改
                </div>
                <!-- END of templatemo_footer_wrapper -->
            </div>
            <!-- END of templatemo_footer -->
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang("zh-cn") }}
{% endblock %}

app/templates/theme_base.html
{% extends "bootstrap/base.html" %}

{% block title %}松学网{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link href="{{ url_for('static', filename="css/templatemo_style.css") }}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block styles %}
    {{ super() }}
{% endblock %}

{% block navbar %}
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">松学网</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">首页</a></li>
                    <li><a href="{{ url_for('course.course_index') }}">课程</a></li>
                    <li><a href="{{ url_for('main.post_index') }}">博文</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.can(Permission.PUBLISH_COURSES) %}
                        <li><a href="{{ url_for('course.application_summary') }}">报名汇总</a></li>
                    {% endif %}
                    {% if current_user.can(Permission.MODERATE_USERS) %}
                        <li><a href="{{ url_for('main.moderate_users') }}">用户审核</a></li>
                    {% endif %}
                    {% if current_user.can(Permission.MODERATE_COMMENTS) %}
                        <li><a href="{{ url_for('main.moderate_comments') }}">评论审核</a></li>
                    {% endif %}
                    {% if current_user.is_authenticated() %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{ current_user.gravatar(size=18) }}">
                                {{ current_user.username }}
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                {% if current_user.can(Permission.PUBLISH_COURSES) %}
                                    <li><a href="{{ url_for('course.publish') }}">发布课程</a></li>
                                {% endif %}
                                <li><a href="{{ url_for('course.applications') }}">我的报名</a></li>
                                {% if current_user.is_authenticated() %}
                                    <li><a href="{{ url_for('main.user', username=current_user.username) }}">个人资料</a>
                                    </li>
                                {% endif %}
                                <li><a href="{{ url_for('auth.change_password') }}">修改密码</a></li>
                                <li><a href="{{ url_for('auth.change_email_request') }}">修改邮箱</a></li>
                                <li><a href="{{ url_for('auth.logout') }}">注销</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div id="home">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
        {% block page_content %}
            <div id="templatemo_main">
                {% block content_main %}
                {% endblock %}
            </div>
        {% endblock %}
        {% block page_footer %}
            <div id="templatemo_bottom_wrapper">
                <div id="templatemo_bottom">
                    <div class="col one_third">
                        <h4><span></span>博客</h4>

                        <div class="bottom_box">
                            <ul class="footer_list">
                                并没有什么博客
                            </ul>
                        </div>
                    </div>
                    <div class="col one_third">
                        <h4><span></span>更新公告</h4>

                        <div class="bottom_box">
                            <ul class="twitter_post">
                                <li>并没有什么更新</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col one_third no_margin_right">
                        <h4><span></span>关于我们</h4>

                        <div class="bottom_box">
                            <p>并没有什么</p>
                        </div>
                    </div>
                    <div class="cleaner"></div>
                </div>
                <!-- END of tempatemo_bottom -->
            </div>
            <!-- END of tempatemo_bottom_wrapper -->
            <div id="templatemo_footer_wrapper">
                <div id="templatemo_footer">
                    Copyright © 2015 松学网 |
                    由 <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a> 设计
                    曾科特 修改
                </div>
                <!-- END of templatemo_footer_wrapper -->
            </div>
            <!-- END of templatemo_footer -->
        {% endblock %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang("zh-cn") }}
{% endblock %}